{
 "title": " - Servidor DNS (Recursivo+CacheDB+Bloqueios Adware)",
 "tags": [
  "unbound",
  "prometheus",
  "loki"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_queries_total{job=\"unbound\"}",
     "legendFormat": "Consultas"
    },
    {
     "expr": "unbound_cache_hit_total{job=\"unbound\"}",
     "legendFormat": "Cache Hits"
    },
    {
     "expr": "unbound_cache_miss_total{job=\"unbound\"}",
     "legendFormat": "Cache Miss"
    },
    {
     "expr": "unbound_prefetch_total{job=\"unbound\"}",
     "legendFormat": "Prefetch"
    },
    {
     "expr": "unbound_expired_total{job=\"unbound\"}",
     "legendFormat": "Expiradas"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_time_up_seconds{job=\"unbound\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(unbound_request_list_current_user{job=\"unbound\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "unbound_recursion_time_avg_seconds{job=\"unbound\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "unbound_request_list_max{job=\"unbound\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "unbound_request_list_avg{job=\"unbound\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_blocklist_domain_count{job=\"unbound\"}",
     "legendFormat": "Lista Bloqueios"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_cache_hit_total{job=\"unbound\"}",
     "legendFormat": "hit"
    },
    {
     "expr": "unbound_cache_miss_total{job=\"unbound\"}",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_query_udpout_count{job=\"unbound\"}",
     "legendFormat": "Consultas UDP"
    },
    {
     "expr": "unbound_query_tcpout_count{job=\"unbound\"}",
     "legendFormat": "Consultas TCP"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(unbound_memory_caches_bytes{job=\"unbound\"})",
     "legendFormat": "Cache Mem"
    },
    {
     "expr": "sum(unbound_memory_modules_bytes{job=\"unbound\"})",
     "legendFormat": "Modules Mem"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_msg_cache_count{job=\"unbound\"}",
     "legendFormat": "Msg Cache"
    },
    {
     "expr": "unbound_rrset_cache_count{job=\"unbound\"}",
     "legendFormat": "RRset Cache"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_infra_cache_count{job=\"unbound\"}",
     "legendFormat": "Infra Cache"
    },
    {
     "expr": "unbound_key_cache_count{job=\"unbound\"}",
     "legendFormat": "Key Cache"
    }
   ]
  },
  {
   "title": "⧉ Intervalo de Tempo de Resposta",
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 0, "y": 5 }
  },
  { "title": "⧉ Tempo de Recursão", "type": "text", "gridPos": { "h": 1, "w": 9, "x": 9, "y": 5 } },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_response_time_buckets{job=\"unbound\"} > 0",
     "legendFormat": "{{lower}} - {{upper}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "unbound_recursion_time_avg_seconds{job=\"unbound\"}",
     "legendFormat": "Média"
    },
    {
     "expr": "unbound_recursion_time_median_seconds{job=\"unbound\"}",
     "legendFormat": "Mediana"
    }
   ]
  },
  {
   "title": "⧉ Consultas por Tipos",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_query_types_count{job=\"unbound\"} > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "⧉ Resposta",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_answer_rcodes_count{job=\"unbound\"} > 0",
     "legendFormat": "{{rcode}}"
    },
    {
     "expr": "unbound_answer_secure_count{job=\"unbound\"} > 0",
     "legendFormat": "secure"
    },
    {
     "expr": "unbound_answer_bogus_count{job=\"unbound\"} > 0",
     "legendFormat": "bogus"
    }
   ]
  },
  {
   "title": "⧉ Consultas",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(dns) (count_over_time({dns=\"reply\"} [$__range]))"
    },
    {
     "expr": "sum by(dns) (count_over_time({dns=\"block\"} [$__range]))"
    }
   ]
  },
  {
   "title": "⧉ Solicitações",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count_over_time({dns=\"reply\"} | pattern `<_> <_> <_> <client> <_> <_> <_> <_> <_> <_> <_>` [$__interval])",
     "legendFormat": "{{client}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "⧉ Consultas",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count_over_time({dns=\"reply\"} [$__interval])",
     "legendFormat": "{{dns}}",
     "resolution": 1
    },
    {
     "expr": "count_over_time({dns=\"block\"} [$__interval])",
     "legendFormat": "{{dns}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "⧉ Clientes Ativos",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(client) (rate({dns=\"reply\"} | pattern `<_> <_> <_> <client> <_> <_> <_> <_> <_> <_> <_>` [$__interval]))",
     "legendFormat": "{{client}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "⧉ Top Consultas",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by(domain, client) (count_over_time({dns=\"reply\"} | pattern `<_> <_> <_> <client> <domain> <_> <_> <_> <_> <_> <_>` [$__range]))"
    }
   ]
  },
  {
   "title": "⧉ Top Bloqueios",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 10, "y": 31 },
   "targets": [
    {
     "expr": "sum by(domain) (count_over_time({dns=\"block\"} | pattern `<_> <_> <_> <domain> <_> <_> <_> <_> <_>` [$__range]))"
    }
   ]
  },
  {
   "title": "⧉ Consultas Ativas",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "{dns=\"reply\"} | pattern `<_> <_> <_> <client> <domain> <type> <_> <_> <lookup_time> <cache> <_>`"
    }
   ]
  },
  {
   "title": "⧉ Bloqueios Ativos",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 10, "y": 43 },
   "targets": [
    {
     "expr": "{dns=\"block\"} | pattern `<_> <_> <_> <domain> <_> <client>@<_> <_> <_> <_>`"
    }
   ]
  }
 ]
}